//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinica.conexion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        public int ID_Cita { get; set; }
        public string Motivo { get; set; }
        public System.DateTime fecha_de_cita { get; set; }
        public Nullable<System.DateTime> fecha_de_generacion { get; set; }
        public int ID_Medico { get; set; }
        public int ID_Paciente { get; set; }
    
        public virtual Medico Medico { get; set; }
        public virtual Paciente Paciente { get; set; }
    }
}
